title: Sobhan Ebrahimi's Homepage
page-top-title: Sobhan Ebrahimi
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
