title: Sobhan Ebrahimi Azar's Homepage
page-top-title: Sobhan Ebrahimi Azar
top-section-bg-text: Computer Science
home-subtitle: Sobhan Ebrahimi Azar &ensp;|&ensp; سبحان ابراهیمی آذر
copyright-text: '&copy; Sobhan Ebrahimi Azar 2023-2024. All Rights Reserved.'
